---
- name: Generate Cisco IOS OS Report
  hosts: "{{ cisco_router }}"
  connection: local
  gather_facts: no

  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        authorize: yes
        commands:
          - show ip int br
